version: "3"
services:
  api: 
    build: .
    ports: []
      - 8000:8000
    #env_file:
    #  - ./.env  
    environment:
      - DATABASE_HOSTNAME=localhost
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=G1bsonsg!
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=a0ee03458a0009eb099ecc1001bee90c9901
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30