"""add_phone_number

Revision ID: 711708910f7e
Revises: fed022e84b34
Create Date: 2022-02-16 17:02:30.061499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '711708910f7e'
down_revision = 'fed022e84b34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
