"""add phone number

Revision ID: fed022e84b34
Revises: 8e221e5e3031
Create Date: 2022-02-16 16:58:14.665465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fed022e84b34'
down_revision = '8e221e5e3031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
